version: '3'
services:
  api1: # API - Instância 01
    image: ftsuda/rinha-backend:1.0.0
    hostname: api1
    depends_on:
      - db
    expose:
      - "8080"
    ports:
      - "8081:8080"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    environment:
      INSTANCIA_ROLE: "principal"
      JDK_JAVA_OPTIONS: "-XX:+UseCompressedClassPointers -XX:+UseZGC -XX:+ZUncommit -XX:+UseDynamicNumberOfGCThreads -XX:-OmitStackTraceInFastThrow -XX:+OptimizeStringConcat -server -ea -XX:+UseContainerSupport -XX:MaxRAMPercentage=80 -XX:+HeapDumpOnOutOfMemoryError"
      DB_POOL_SIZE_INITIAL: "100"
      DB_POOL_SIZE_MAX: "100"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '750MB'

  api2: # API - Instância 02
    image: ftsuda/rinha-backend:1.0.0
    hostname: api2
    depends_on:
      - db
    expose:
      - "8080"
    ports:
      - "8082:8080"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    environment:
      INSTANCIA_ROLE: "secundaria"
      JDK_JAVA_OPTIONS: "-XX:+UseCompressedClassPointers -XX:+UseZGC -XX:+ZUncommit -XX:+UseDynamicNumberOfGCThreads -XX:-OmitStackTraceInFastThrow -XX:+OptimizeStringConcat -server -ea -XX:+UseContainerSupport -XX:MaxRAMPercentage=80 -XX:+HeapDumpOnOutOfMemoryError"
      DB_POOL_SIZE_INITIAL: "100"
      DB_POOL_SIZE_MAX: "100"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '750MB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500MB'

  db: # Banco de dados
    image: postgres
    command: postgres -c config_file=/postgresql.conf
    volumes:
      - ./postgresql.conf:/postgresql.conf
    environment:
      POSTGRES_DB: "rinha"
      POSTGRES_USER: "rinha_user"
      POSTGRES_PASSWORD: "rinha_pwd"
    expose:
      - "5432"
    ports:
      - "5434:5432"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1GB'
